apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
    - password=TYPE_YOUR_PASSWORD
    - userpass=TYPE_YOUR_PASSWORD
resources:
  - pvc1.yaml
  - pvc2.yaml
  - mysql.yaml
  - wordpress.yaml